[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "python"
roots = [ "pyproject.toml" ]
language-servers = [ "pyright", "ruff" ]

[language-server.gpt]
command = "bun"
args = ["run", "~/.local/bin/helix-gpt", "--handler", "copilot", "${HANDLER}", "--copilotApiKey", "${COPILOT_API_KEY}"]

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
run = "onSave"
args = [ "--ignore", "E501" ]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
