##############################
## Configuration for lsp-ai ##
##############################

[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.model1]
type = "open_ai"
chat_endpoint = "https://api.runpod.ai/v2/vllm-sc4t0jabjte3mq/openai/v1"
model =  "Qwen/CodeQwen1.5-7B-AWQ"
auth_token_env_var_name = "COPILOT_OPENAI_API_KEY"

[language-server.lsp-ai.config.completion]
model = "model1"

[language-server.lsp-ai.config.completion.parameters]
max_tokens = 64
max_context = 1024

#################################
## Configuration for languages ##
#################################

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = [ "lsp-ai" ]

[[language]]
name = "python"
roots = [ "pyproject.toml" ]
language-servers = [ "pyright", "ruff", "lsp-ai" ]

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
run = "onSave"
args = [ "--ignore", "E501" ]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
