[font]
size = 14.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"

[window]
decorations = "buttonless"
option_as_alt = "OnlyLeft"

[window.padding]
x = 3
y = 5

[[keyboard.bindings]]
key = "Space"
mods = "Command|Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "K"
mods = "Command"
command = "~/.config/alacritty/reset-alacritty"

# [keyboard]
# bindings = [
#   { key = "K", mods = "Command", chars = "\u001bc" },
#   { key = "L", mods = "Command", action = "ClearHistory"},
# ]
