#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="10"
gaps["bottom"]="24"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="8"
gaps["inner"]="4"
#gaps["inner"]="0"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"


color["focused"]="0xfff00031"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"
color["transparent"]="0x00FFFFFF"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# ===== Sketchybar settings ====================

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/dotfiles/config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/dotfiles/config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config external_bar                all:35:0

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"

# yabai -m config debug_output on # debug

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_zoom_persist         off
yabai -m config window_placement            second_child
 
yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
# yabai -m config active_window_border_color  "${color["focused"]}"
# yabai -m config normal_window_border_color  "${color["normal"]}"
# yabai -m config insert_feedback_color       "${color["preselect"]}"
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "${color["transparent"]}"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================

yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|System Settings|Bitwarden|KeePassXC|mpv|IINA|Dash|JetBrains Toolbox|iStat|Copy|Stats|Dota 2|The Unarchiver|Bin)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Raycast" app="^Raycast$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Craft" app="^Craft$" title="(Settings|Info)" manage=off
yabai -m rule --add label="Scoot" app="^Scoot$" manage=off
yabai -m rule --add label="Homerow" app="^Homerow$" manage=off
yabai -m rule --add label="Orion" app="^(Orion RC|Orion)$" title="^(General|(Tab|Password|Website|Extension|Plu|Bookmark|Profile)s|AutoFill|Se(arch|curity)|Privacy|Advance|Browsing|Sync|History|Reading List)$" manage=off
# yabai -m rule --add label="Arc" app="^Arc$" title="^(Albert|General|Shortcuts|Little Arc|Advanced)$" manage=off
# yabai -m rule --add label="Arc - PiP" app="^Arc$" level=3 title="Arc" manage=off
# ===== Signals ================================
# ===== Ubersicht 
# yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

set +x
printf "yabai: configuration loaded...\\n"
